#!/bin/bash
#PBS -l select=1:ncpus=8:ngpus=1:mem=32gb
#PBS -l walltime=12:00:00
#PBS -q normal
#PBS -P personal
#PBS -o output_inferppo.log           
#PBS -e error_inferppo.log  
#PBS -N ppo_inference

module load miniforge3/25.3.1

module load cuda/11.8.0

source activate parkinson

cd /home/users/ntu/s250045/scratch/MedicalGPT

python inference.py \
    --base_model ./merged-ppo-parkinson \
    --data_file ./parkinson_real_questions_v2.jsonl \
    --output_file ./ppo_eval_results.jsonl \
    --max_new_tokens 1024