#!/bin/bash
#PBS -q normal
#PBS -P personal
#PBS -l select=1:ncpus=24:mem=60g:ngpus=1
#PBS -l walltime=24:00:00
#PBS -N Infer_SFT
#PBS -o output_infer_sft.log
#PBS -e error_infer_sft.log

cd $PBS_O_WORKDIR

module load miniforge3/25.3.1
module load cuda/11.8.0

source activate parkinson

export HF_ENDPOINT=https://hf-mirror.com

echo "=== Starting SFT Model Inference ==="
CUDA_VISIBLE_DEVICES=0 python inference.py --base_model merged-sft-parkinson --data_file questions.txt --output_file output_sft.jsonl --max_new_tokens 512
echo "=== SFT Model Inference Finished ==="
